<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to the %sVeeam Software%s test application'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo $this->translate('This is the application for Veeam Software, which I had done during my recruitment process in September 2014.')?></p>
    <p><?php echo $this->translate('The application is a list of job offers. Each job offer has a department property, and may be translated to different languages. The list has a filter, which allows to find items either by a department or by a language. If an offer isn\'t translated to some language, it\'s displayed in the list in English.')?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/ikarpovich/veeam-test" target="_blank"><?php echo $this->translate('The source code on GitHub') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Search for a job') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Let\'s go and %sfind%s some jobs! Isn\'t the main purpose of this app?'), '<a href="'.$this->url('veeam-test').'">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('veeam-test')?>" target="_blank"><?php echo $this->translate('Search for a job') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Manage jobs') ?></h3>
            </div>
            <div class="panel-body">
                <p>Maybe later :)</p>
            </div>
        </div>
    </div>
</div>
