<h1>Find jobs</h1>


<?php
$form = $this->searchForm;
$this->form()->openTag($form);?>
<?php echo $this->form()->closeTag() ?>
<form class="form-inline" role="form">
    <div class="form-group">
        <?php
        $department = $form->get('department');
        $department->setAttributes(array("class"=>"form-control", "id"=>"departmentInput"));
        ?>
        <label class="sr-only" for="departmentInput"><?php echo $department->getOption('label');?></label>
        <?php echo $this->formSelect($department);?>
    </div>
    <div class="form-group">
        <?php
        $language = $form->get('language');
        $language->setAttributes(array("class"=>"form-control", "id"=>"languageInput"));
        ?>
        <label class="sr-only" for="languageInput"><?php echo $department->getOption('label');?></label>
        <?php echo $this->formSelect($language);?>
    </div>
    <?php echo $this->formElement($form->get('security')) ?>
    <?php
    $send=$form->get('send');
    $send->setAttributes(array("class"=>"btn btn-default"));
    echo $this->formElement($send) ?>
</form>

<h2>Search results</h2>

<div class="list-group job-list">
    <div class="list-group-item">
        <h4>Job #1 <span class="label label-info">Department 1</span></h4>
        <div class="job-description">
            <p>Job Description</p>
        </div>
    </div>

    <div class="list-group-item">
        <h4>Job #2 <span class="label label-info">Department 2</span></h4>
        <div class="job-description">
            <p>Job Description</p>
        </div>
    </div>

</div>